language: c++
matrix:
  include:
    - name: "linux cmake gcc"
      os: linux
      dist: xenial
      compiler: gcc
      sudo: required
      script:
        - mkdir build
        - cd ./build
        - cmake ..
        - cmake --build .

    - name: "linux cmake clang"
      os: linux
      dist: xenial
      compiler: clang
      sudo: required
      script:
        - mkdir build
        - cd ./build
        - cmake ..
        - cmake --build .